### ISSUE TITLE
Extend Rust operators and SWAG traits to account for lift and lower

### ISSUE THREAD

**Issue by scotts** [IBM/sliding-window-aggregators#42]
The current Rust traits do not allow for the full type flexibility in the published algorithms and what are currently in our C++ implementations. Specifically, the Rust traits assume that the type that is inserted is necessarily the same as the return type of a query. The implementations also use the same type for storing partial results.

In our papers, we introduced the _lift_ operation which converts an input type `In` into the stored type `Partial`. The `Partial` type is stored in the window, and the aggregation operator is a binary function on the `Partial` type. We also introduced the _lower_ operation which converts the `Partial` type into the `Out` type. In the SWAG, we insert `In` types, and internally we use _lift_ to convert those into `Partial`s. Queries return values of type `Out`, and use _lower_ to turn a `Partial` into `Out`.

I was forced to contend with this when I started implementing a mean operator in Rust, as the input type is a number (say, `i32`), but the partial type must have a sum and count (say, `{sum: i32, count: usize}`). What I have currently is:

```
#[derive(Copy, Clone)]
pub struct Mean;

#[derive(Copy, Clone, Eq, PartialEq)]
struct MeanPartial<T> {
    sum: T,
    n: usize,
}
```
Even if we assume the above trait issue regarding lift and lower is solved, extending this approach starts to get awkward. The binary function must be defined on `MeanPartial`:

```
impl AbstractMagma<Mean> for MeanPartial<i32> {
    fn operate(&self, other: &Self) -> Self {
        MeanPartial::<i32>{sum: self.sum + other.sum,
                           n: self.n + other.n}
    }
}
```
By itself, that's not a problem. But having to define things in terms of `MeanPartial` will extend everywhere. The main problem I see is that the partial type is exposed to the user who creates a window. For example, even if we assume that the current traits allow for all three types, users would have to do something like `TwoStacks::<i32, MeanPartial<i32>, i32, Mean>` when specifying a window's type.

In C++, we "hid" the partial definition inside of the operator. Window implementations knew they could ask the operator what its partial type is. I am going to explore a similar approach in Rust, so that users will be able to do something closer to `TwoStacks::<Mean<i32>>`.

@segeljakt, I'll let you know when I have something concrete so I can get your feedback.

**Comment by segeljakt** [comment]
I see what you mean. There should be a solution to hide the MeanPartial. I am wondering if we can use associated types: https://doc.rust-lang.org/rust-by-example/generics/assoc_items/types.html. They are useful in cases where the type of one type parameter implies the type of another. In this case `Mean` and `i32` should imply `MeanPartial<i32>`.

**Comment by scotts** [comment]
I think associated types are promising - I encountered them when reading up on Rust generics, and it seems to fit our user-case. I'm currently still trying to get my head around how to make this new trait that specifies lifting and lower (and implies the partial) be independent of but work with the monoid trait.

**Comment by segeljakt** [comment]
It might for example be possible to define a sub-trait "`MapWindow`" of `FifoWindow`. This implementation below exposes the partials but hides the input and output types. I think it should be possible to achieve the opposite so that only the input and/or output type + binary operator is visible:
```rust
// Lift Self into T
trait Lift<T> {
    fn lift(self) -> T;
}

// Lower T into Self
trait Lower<T> {
    fn lower(v: T) -> Self;
}

trait MapWindow<Partial, BinOp>: FifoWindow<Partial, BinOp>
where
    BinOp: Operator,
{
    type Input: Lift<Partial>;
    type Output: Lower<Partial>;
    fn new() -> Self {
        <Self as FifoWindow<Partial, BinOp>>::new()
    }
    fn name() -> &'static str {
        <Self as FifoWindow<Partial, BinOp>>::name()
    }
    fn push(&mut self, v: Self::Input) {
        <Self as FifoWindow<Partial, BinOp>>::push(self, Self::Input::lift(v))
    }
    fn pop(&mut self) -> Option<Partial> {
        <Self as FifoWindow<Partial, BinOp>>::pop(self)
    }
    fn query(&self) -> Self::Output {
        Self::Output::lower(<Self as FifoWindow<Partial, BinOp>>::query(self))
    }
    fn len(&self) -> usize {
        <Self as FifoWindow<Partial, BinOp>>::len(self)
    }
    fn is_empty(&self) -> bool {
        <Self as FifoWindow<Partial, BinOp>>::is_empty(self)
    }
}

#[derive(Clone)]
struct MeanPartial<T> {
    sum: T,
    count: u32,
}

impl Lift<MeanPartial<i32>> for i32 {
    fn lift(self) -> MeanPartial<i32> {
        MeanPartial { sum: self, count: 1 }
    }
}

impl Lower<MeanPartial<i32>> for i32 {
    fn lower(v: MeanPartial<i32>) -> i32 {
        v.sum / (v.count as i32)
    }
}

#[derive(Copy,Clone)]
pub struct Mean;

impl Mean {
    pub fn name() -> &'static str {
        "mean"
    }
}

// impl alga::* for Mean

fn test() {
    let win = two_stacks::TwoStacks::<MeanPartial<i32>, Mean>::new();
}
```

**Comment by segeljakt** [comment]
Hmm now that I think about it, there might a problem here, I forgot the `impl MapWindow for TwoStacks` 👀

**Comment by segeljakt** [comment]
Here is an updated version which compiles. It can likely be improved:
```rust
trait Lift<T> {
    fn lift(self) -> T;
}

trait Lower<T> {
    fn lower(v: T) -> Self;
}

trait PartialOf<Input, Output, BinOp> {}

trait Window<Partial, Input, Output, BinOp>: FifoWindow<Partial, BinOp>
where
    BinOp: Operator,
    Input: Lift<Partial>,
    Output: Lower<Partial>,
    Partial: PartialOf<Input, Output, BinOp>,
{
    fn create() -> Self {
        <Self as FifoWindow<Partial, BinOp>>::new()
    }
    fn push_and_lift(&mut self, v: Input) {
        <Self as FifoWindow<Partial, BinOp>>::push(self, Input::lift(v))
    }
    fn query_and_lower(&self) -> Output {
        Output::lower(<Self as FifoWindow<Partial, BinOp>>::query(self))
    }
}

impl<Partial, Input, Output, BinOp> Window<Partial, Input, Output, BinOp>
    for two_stacks::TwoStacks<Partial, BinOp>
where
    BinOp: Operator,
    Input: Lift<Partial>,
    Output: Lower<Partial>,
    Partial: AbstractMonoid<BinOp>,
    Partial: PartialOf<Input, Output, BinOp>,
{
}

#[derive(Clone, PartialEq, Eq)]
struct MeanPartial<T: PartialEq + Eq> {
    sum: T,
    count: u32,
}

impl<Input> PartialOf<Input, Input, Mean> for MeanPartial<Input> where Input: Eq + PartialEq {}

impl Lift<MeanPartial<i32>> for i32 {
    fn lift(self) -> MeanPartial<i32> {
        MeanPartial {
            sum: self,
            count: 1,
        }
    }
}

impl Lower<MeanPartial<i32>> for i32 {
    fn lower(v: MeanPartial<i32>) -> i32 {
        v.sum / (v.count as i32)
    }
}

use alga::general::*;

#[derive(Copy, Clone)]
pub struct Mean;

impl Mean {
    pub fn name() -> &'static str {
        "mean"
    }
}

impl Operator for Mean {
    fn operator_token() -> Self {
        Mean
    }
}

impl Identity<Mean> for MeanPartial<i32> {
    fn identity() -> MeanPartial<i32> {
        MeanPartial { sum: 0, count: 1 }
    }
}

impl AbstractMagma<Mean> for MeanPartial<i32> {
    fn operate(&self, other: &Self) -> Self {
        MeanPartial {
            sum: self.sum + other.sum,
            count: self.count + other.count,
        }
    }
}

impl AbstractSemigroup<Mean> for MeanPartial<i32> {}
impl AbstractMonoid<Mean> for MeanPartial<i32> {}

fn test() {
    let mut win = two_stacks::TwoStacks::<MeanPartial<i32>, Mean>::create();
    let x: i32 = 3;
    win.push_and_lift(x);
    win.query_and_lower();
}
```

**Comment by scotts** [comment]
I'm not a fan on defining `MapWindow` which just forwards everything to `FifoWindow`. I think that will get out of hand. What I'm experimenting with is a trait for lifting and lowering:

```
pub trait AggregationFunction<In, Out> {
    type Partial;

    fn lift(&self, val: In) -> Self::Partial;
    fn lower(&self, part: &Self::Partial) -> Out;
}
```

And then aggregation functions implement that trait. The requirements in the implementation of the `FifoWindow` then become something like `AbstractMonoid<BinOp> + AggregationFunction<BinOp> + Clone`.

**Comment by scotts** [comment]
Your ideas are a lot further along than mine - yours compile! But two things I've convinced myself of (but I may change my mind):

1. The lift and lower operations are fundamentally linked, since they both involve the same partial. I don't think it makes sense to ever define them in isolation, which means I think they should be in the same trait.
2. I think it's less confusing if `FifoWindow` knows about this trait, rather than preserving `FifoWindow` as-is and making a wrapper.

I'm still trying to make something work, but I'm also learning how to think in Rust traits while I do it, so it may take a few days before I get something that makes sense.

**Comment by segeljakt** [comment]
The trait system can take some time to get used to. I'm just hammering code while until the Rust compiler does not reject it 😂 
 If you are not already using it, I recommend [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer). I could not live without it.

I agree with the points. It is probably warranted to update the `FifoWindow` trait and keep the lift/lower functions together under one trait.
